# Generated by Django 3.1.5 on 2021-04-03 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=250)),
                ('location', models.CharField(default='Not Specified', max_length=250)),
                ('contact', models.CharField(default='Not Specified', max_length=250)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=250)),
                ('ip_address', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('protocol', models.CharField(max_length=250)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
            options={
                'db_table': 'device_interfaces',
            },
        ),
        migrations.CreateModel(
            name='DeviceSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('secret', models.CharField(max_length=250)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
            options={
                'db_table': 'device_security',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.date(2021, 4, 3))),
                ('time', models.TimeField(default=datetime.time(19, 42, 28, 591843))),
                ('flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert',
            },
        ),
    ]
