# Generated by Django 3.1.5 on 2021-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device-manager', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('deviceType', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=250)),
            ],
        ),
    ]
