# Generated by Django 3.1.5 on 2021-01-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device-manager',
            new_name='device',
        ),
    ]
