# Generated by Django 3.1.5 on 2021-04-03 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.TimeField(default=datetime.time(19, 44, 3, 132282)),
        ),
    ]
