# Generated by Django 3.1.5 on 2021-01-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210125_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='contact',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
