# Generated by Django 3.1.5 on 2021-01-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210126_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='contact',
            field=models.CharField(default='Not Specified', max_length=250),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(default='Not Specified', max_length=250),
        ),
    ]
