# Generated by Django 3.1.5 on 2021-04-03 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210403_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.TimeField(default=datetime.time(19, 47, 37, 543919)),
        ),
        migrations.AlterModelTable(
            name='security',
            table='security',
        ),
    ]
