# Generated by Django 3.1.5 on 2021-04-03 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20210403_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.TimeField(default=datetime.time(20, 5, 45, 752026)),
        ),
        migrations.AlterModelTable(
            name='alert',
            table=None,
        ),
        migrations.AlterModelTable(
            name='device',
            table=None,
        ),
        migrations.AlterModelTable(
            name='interface',
            table=None,
        ),
        migrations.AlterModelTable(
            name='security',
            table=None,
        ),
    ]
