# Generated by Django 3.1.5 on 2021-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20210126_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
