# Generated by Django 3.1.5 on 2021-04-03 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20210403_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.TimeField(default=datetime.time(20, 20, 1, 500624)),
        ),
        migrations.DeleteModel(
            name='Interface',
        ),
    ]
