# Generated by Django 3.1.5 on 2021-02-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20210215_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
