# Generated by Django 3.1.5 on 2021-04-04 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20210403_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 4)),
        ),
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.TimeField(default=datetime.time(14, 2, 7, 484882)),
        ),
    ]
