# Generated by Django 3.1.5 on 2021-02-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20210215_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
    ]
