# Generated by Django 3.1.5 on 2021-02-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_auto_20210215_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='username',
        ),
    ]
