# Generated by Django 3.1.5 on 2021-03-09 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
