# Generated by Django 3.1.5 on 2021-03-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_auto_20210309_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='code',
            new_name='type',
        ),
    ]
