# Generated by Django 3.1.5 on 2021-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_auto_20210309_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.IntegerField(default=8351, max_length=6, primary_key=True, serialize=False),
        ),
    ]
