# Generated by Django 3.1.5 on 2021-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0016_auto_20210309_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
