# Generated by Django 3.1.5 on 2021-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_auto_20210317_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
