# Generated by Django 3.1.5 on 2021-03-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_device_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
