# Generated by Django 3.1.5 on 2021-03-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0022_delete_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
    ]
