# Generated by Django 3.1.5 on 2021-03-23 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0024_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 23)),
        ),
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.time(15, 26, 5, 197213)),
        ),
    ]
