# Generated by Django 3.1.5 on 2021-03-23 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0025_auto_20210323_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.time(16, 33, 11, 583212)),
        ),
    ]
