# Generated by Django 3.1.5 on 2021-03-24 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0026_auto_20210323_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 24)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.time(12, 39, 22, 252119)),
        ),
    ]
