# Generated by Django 3.1.5 on 2021-03-24 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0027_auto_20210324_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.time(12, 46, 23, 225645)),
        ),
    ]
