# Generated by Django 3.1.5 on 2021-03-25 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0028_auto_20210324_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='time',
        ),
        migrations.AddField(
            model_name='log',
            name='dateTime',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 13, 31, 31, 511421)),
        ),
    ]
