# Generated by Django 3.1.5 on 2021-03-25 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0029_auto_20210325_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 33, 18, 117157)),
        ),
    ]
