# Generated by Django 3.1.5 on 2021-03-26 16:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0030_auto_20210325_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 16, 41, 34, 24784)),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=250)),
                ('deviceType', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=250)),
                ('location', models.CharField(default='Not Specified', max_length=250)),
                ('contact', models.CharField(default='Not Specified', max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('secret', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
