# Generated by Django 3.1.5 on 2021-04-01 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0034_auto_20210401_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 1)),
        ),
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.time(14, 47, 46, 202767)),
        ),
    ]
