# Generated by Django 3.1.5 on 2021-04-01 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0035_auto_20210401_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.time(13, 55, 26, 2684)),
        ),
    ]
