# Generated by Django 3.1.5 on 2021-03-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=250)),
                ('deviceType', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=250)),
                ('location', models.CharField(default='Not Specified', max_length=250)),
                ('contact', models.CharField(default='Not Specified', max_length=250)),
                ('status', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
