# Generated by Django 3.1.5 on 2021-03-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_device_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='User',
            new_name='user',
        ),
    ]
