# Generated by Django 3.1.5 on 2021-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210321_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='Not Set', max_length=250),
        ),
        migrations.AddField(
            model_name='device',
            name='secret',
            field=models.CharField(default='Not Set', max_length=250),
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(default='Not Set', max_length=250),
        ),
    ]
