# Generated by Django 3.1.5 on 2021-03-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210323_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device',
            new_name='deviceName',
        ),
    ]
