# Generated by Django 3.1.5 on 2021-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210324_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='device',
            name='secret',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
