# Generated by Django 3.1.5 on 2021-03-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20210324_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
