# Generated by Django 3.1.5 on 2021-04-05 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.TimeField(default=datetime.time(18, 5, 16, 693385)),
        ),
        migrations.AlterField(
            model_name='security',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='secret',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
