# Generated by Django 3.1.5 on 2021-04-05 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20210405_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.TimeField(default=datetime.time(20, 59, 29, 495083)),
        ),
    ]
