# Generated by Django 3.1.3 on 2020-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201121_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='subnet',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
