# Generated by Django 3.1.4 on 2020-12-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_interface_subnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='interfaces',
        ),
        migrations.AddField(
            model_name='device',
            name='host',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Interface',
        ),
    ]
